package view;

import dao.DienThoaiDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.DienThoai;

public class FormAddProduct extends javax.swing.JDialog {

    /**
     * Creates new form ThemSP
     */
    private LayoutProduct owner;

    public FormAddProduct(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.owner = (LayoutProduct) parent;
        initComponents();
        setLocationRelativeTo(null);
        txtMaDienThoai.setText(createIdDienThoai());
    }

    private FormAddProduct(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMaDienThoai = new javax.swing.JLabel();
        txtMaDienThoai = new javax.swing.JTextField();
        labelTenDienThoai = new javax.swing.JLabel();
        txtTenDienThoai = new javax.swing.JTextField();
        labelGia = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        labelHang = new javax.swing.JLabel();
        cbxHang = new javax.swing.JComboBox<>();
        labelChipXuLy = new javax.swing.JLabel();
        txtChipXuLy = new javax.swing.JTextField();
        labelRAM = new javax.swing.JLabel();
        cbxRAM = new javax.swing.JComboBox<>();
        labelROM = new javax.swing.JLabel();
        cbxROM = new javax.swing.JComboBox<>();
        labelHeDieuHanh = new javax.swing.JLabel();
        txtHeDieuHanh = new javax.swing.JTextField();
        labelCameraChinh = new javax.swing.JLabel();
        txtCameraChinh = new javax.swing.JTextField();
        labelCameraPhu = new javax.swing.JLabel();
        txtCameraPhu = new javax.swing.JTextField();
        labelKichThuocMan = new javax.swing.JLabel();
        txtKichThuocMan = new javax.swing.JTextField();
        labelDungLuongPin = new javax.swing.JLabel();
        txtDungLuongPin = new javax.swing.JTextField();
        labelXuatXu = new javax.swing.JLabel();
        cbxXuatXu = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm điện thoại mới");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelMaDienThoai.setText("Mã điện thoại");

        txtMaDienThoai.setEditable(false);
        txtMaDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDienThoaiActionPerformed(evt);
            }
        });

        labelTenDienThoai.setText("Tên điện thoại");

        labelGia.setText("Giá");

        labelHang.setText("Hãng");

        cbxHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Samsung", "Xiaomi", "OPPO", "Vivo", "Realme", "Nokia", "Sony", "Motorola", "Honor" }));

        labelChipXuLy.setText("Chip xử lý");

        labelRAM.setText("RAM");

        cbxRAM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 GB", "3 GB", "4 GB", "6 GB", "8 GB", "12 GB", "16 GB", "18 GB", "24 GB", "32 GB" }));

        labelROM.setText("ROM");

        cbxROM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32 GB", "64 GB", "128 GB", "256 GB", "512 GB", "1 TB", "2 TB", "4 TB", "8 TB", "16 TB" }));

        labelHeDieuHanh.setText("Hệ điều hành");

        labelCameraChinh.setText("Camera chính");

        labelCameraPhu.setText("Camera phụ");

        labelKichThuocMan.setText("Kích thước màn");

        labelDungLuongPin.setText("Dung lượng PIN");

        labelXuatXu.setText("Xuất xứ");

        cbxXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trung Quốc", "Việt Nam", "Hàn Quốc", "Nhật Bản", "Mỹ", "Đài Loan", "Thái Lan", "Ấn Độ", "Phần Lan", "Indonesia" }));

        btnAddProduct.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Thêm điện thoại");
        btnAddProduct.setBorder(null);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Huỷ bỏ");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMaDienThoai))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTenDienThoai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelChipXuLy)
                            .addComponent(txtChipXuLy, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelGia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKichThuocMan)
                            .addComponent(txtKichThuocMan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCameraChinh)
                            .addComponent(txtCameraChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHeDieuHanh)
                            .addComponent(txtHeDieuHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxHang, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCameraPhu)
                    .addComponent(txtCameraPhu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelROM)
                    .addComponent(cbxROM, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaDienThoai)
                            .addComponent(labelHang))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTenDienThoai)
                        .addGap(6, 6, 6)
                        .addComponent(txtTenDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelRAM)
                            .addGap(6, 6, 6)
                            .addComponent(cbxRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelChipXuLy)
                            .addGap(4, 4, 4)
                            .addComponent(txtChipXuLy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelROM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxROM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelKichThuocMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKichThuocMan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCameraChinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCameraChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCameraPhu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCameraPhu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDungLuongPin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelHeDieuHanh)
                        .addGap(4, 4, 4)
                        .addComponent(txtHeDieuHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelXuatXu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelGia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 880, 420));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÊM ĐIỆN THOẠI MỚI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(285, 285, 285))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // Get all values from form
        String maDienThoai = txtMaDienThoai.getText().trim();
        String tenDienThoai = txtTenDienThoai.getText().trim();
        String hang = (String) cbxHang.getSelectedItem();
        String ram = (String) cbxRAM.getSelectedItem();
        String rom = (String) cbxROM.getSelectedItem();
        String chipXuLy = txtChipXuLy.getText().trim();
        String heDieuHanh = txtHeDieuHanh.getText().trim();
        String cameraChinh = txtCameraChinh.getText().trim();
        String cameraPhu = txtCameraPhu.getText().trim();
        String dungLuongPin = txtDungLuongPin.getText().trim();
        String xuatXu = (String) cbxXuatXu.getSelectedItem();
        
        // Validate required fields
        if (tenDienThoai.isEmpty() || chipXuLy.isEmpty() || heDieuHanh.isEmpty() || 
            cameraChinh.isEmpty() || cameraPhu.isEmpty() || dungLuongPin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", 
                                        "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validate and parse price
        double gia = 0;
        try {
            String giaText = txtGia.getText().trim();
            if (giaText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giá sản phẩm!", 
                                            "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            gia = Double.parseDouble(giaText);
            if (gia <= 0) {
                JOptionPane.showMessageDialog(this, "Giá sản phẩm phải lớn hơn 0!", 
                                            "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá ở dạng số!", 
                                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate and parse screen size
        double kichThuocMan = 0;
        try {
            String kichThuocText = txtKichThuocMan.getText().trim();
            if (kichThuocText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập kích thước màn hình!", 
                                            "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            kichThuocMan = Double.parseDouble(kichThuocText);
            if (kichThuocMan <= 0) {
                JOptionPane.showMessageDialog(this, "Kích thước màn hình phải lớn hơn 0!", 
                                            "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kích thước màn hình ở dạng số!", 
                                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create DienThoai object
        DienThoai dt = new DienThoai(
            maDienThoai,
            tenDienThoai,
            0,              // soLuong starts at 0
            hang,
            dungLuongPin,
            ram,
            rom,
            kichThuocMan,
            cameraChinh,
            cameraPhu,
            chipXuLy,
            heDieuHanh,
            gia,
            xuatXu,
            1               // trangThai = 1 (active)
        );
        
        // Insert into database
        try {
            int result = DienThoaiDAO.getInstance().insert(dt);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Thêm điện thoại thành công!", 
                                            "Thành công", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                if (owner != null) {
                    owner.loadDataToTable();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Thêm điện thoại thất bại!", 
                                            "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), 
                                        "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void txtMaDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDienThoaiActionPerformed

    /**
     * Generate unique ID for new phone
     */
    public String createIdDienThoai() {
        ArrayList<DienThoai> dtAll = DienThoaiDAO.getInstance().selectAll();
        int i = dtAll.size() + 1;
        String newId = "DT" + i;
        
        // Check if ID already exists
        boolean exists = true;
        while (exists) {
            exists = false;
            for (DienThoai dt : dtAll) {
                if (dt.getMaDienThoai().equals(newId)) {
                    exists = true;
                    i++;
                    newId = "DT" + i;
                    break;
                }
            }
        }
        return newId;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAddProduct dialog = new FormAddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbxHang;
    private javax.swing.JComboBox<String> cbxRAM;
    private javax.swing.JComboBox<String> cbxROM;
    private javax.swing.JComboBox<String> cbxXuatXu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCameraChinh;
    private javax.swing.JLabel labelCameraPhu;
    private javax.swing.JLabel labelChipXuLy;
    private javax.swing.JLabel labelDungLuongPin;
    private javax.swing.JLabel labelGia;
    private javax.swing.JLabel labelHang;
    private javax.swing.JLabel labelHeDieuHanh;
    private javax.swing.JLabel labelKichThuocMan;
    private javax.swing.JLabel labelMaDienThoai;
    private javax.swing.JLabel labelRAM;
    private javax.swing.JLabel labelROM;
    private javax.swing.JLabel labelTenDienThoai;
    private javax.swing.JLabel labelXuatXu;
    private javax.swing.JTextField txtCameraChinh;
    private javax.swing.JTextField txtCameraPhu;
    private javax.swing.JTextField txtChipXuLy;
    private javax.swing.JTextField txtDungLuongPin;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHeDieuHanh;
    private javax.swing.JTextField txtKichThuocMan;
    private javax.swing.JTextField txtMaDienThoai;
    private javax.swing.JTextField txtTenDienThoai;
    // End of variables declaration//GEN-END:variables
}
