package UI;

import DAO.ProductDAO;
import DAO.SupplierDAO;
import Model.Product;
import Util.DateTimeUtil;
import Util.IconScaler;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PurchasePage extends javax.swing.JPanel {

    Product productDTO;
    String username = null;
    String supplier = null;
    Dashboard dashboard;
    int quantity;
    String prodCode = null;
    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
    /**
     * Creates new form PurchasePage
     */
    
    public PurchasePage(Dashboard dashboard) {
        initComponents();
        this.dashboard = dashboard;
        purchaseTable.setDefaultEditor(Object.class, null);
        purchaseTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        refreshButton.setIcon(IconScaler.scaleIcon16("/UI/Icons/refresh.png"));
        initTable();
        loadComboBox();
        loadProductComboBox();
        loadDataSet();
    }
    
    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã nhập", "Ngày", "Mã SP", "Tên SP", "Mã NCC", "Tên NCC", "Số lượng", "Giá nhập", "Tổng chi phí"};
        tblModel.setColumnIdentifiers(headerTbl);
        purchaseTable.setModel(tblModel);
        purchaseTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        purchaseTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        purchaseTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        purchaseTable.getColumnModel().getColumn(3).setPreferredWidth(250);
        purchaseTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        purchaseTable.getColumnModel().getColumn(5).setPreferredWidth(200);
        purchaseTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        purchaseTable.getColumnModel().getColumn(7).setPreferredWidth(120);
        purchaseTable.getColumnModel().getColumn(8).setPreferredWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        suppCombo = new javax.swing.JComboBox<>();
        prodCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        quantityText = new javax.swing.JTextField();
        costText = new javax.swing.JTextField();
        brandText = new javax.swing.JTextField();
        purchaseButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel1.setText("NHẬP HÀNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập hàng"));

        jLabel2.setText("Nhà cung cấp:");

        suppCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn sản phẩm" }));
        prodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Sản phẩm:");

        jLabel5.setText("Ngày:");

        jLabel6.setText("Số lượng:");

        jLabel7.setText("Giá gốc:");

        jLabel9.setText("Hãng:");

        nameText.setEnabled(false);
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        purchaseButton.setBackground(new java.awt.Color(0, 202, 78));
        purchaseButton.setForeground(new java.awt.Color(51, 51, 51));
        purchaseButton.setText("NHẬP");
        purchaseButton.setBorderPainted(false);
        purchaseButton.setOpaque(true);
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 96, 92));
        deleteButton.setForeground(new java.awt.Color(51, 51, 51));
        deleteButton.setText("Xóa");
        deleteButton.setBorderPainted(false);
        deleteButton.setOpaque(true);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suppCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameText))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quantityText))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costText))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(brandText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(purchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suppCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        purchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        purchaseTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        purchaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchaseTable);

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icons/refresh.png"))); // NOI18N
        refreshButton.setText("LÀM MỚI");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });

        jLabel10.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadDataSet();
        loadComboBox();
        loadProductComboBox();
        clearFields(); 
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void clearFields() {
        prodCombo.setSelectedIndex(0);
        nameText.setText("");
        jDateChooser1.setDate(null);
        quantityText.setText("");
        costText.setText("");
        brandText.setText("");
        searchText.setText("");
    }

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        loadSearchData(searchText.getText());
    }//GEN-LAST:event_searchTextKeyReleased

    private void purchaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseTableMouseClicked
        int row = purchaseTable.getSelectedRow();
        int col = purchaseTable.getColumnCount();

        Object[] data = new Object[col];
        for (int i=0; i<col; i++)
            data[i] = purchaseTable.getValueAt(row, i);
        
        try {
            String dateStr = data[1].toString();
            // Parse display format to set date picker
            java.util.Date date = DateTimeUtil.parseDisplayFormat(dateStr);
            if (date != null) {
                jDateChooser1.setDate(date);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Get data from table columns
        String supplierCode = data[4].toString();
        String productCode = data[2].toString();
        String productName = data[3].toString();
        
        // Set supplier combo by matching supplier code
        for (int i = 0; i < suppCombo.getItemCount(); i++) {
            String item = suppCombo.getItemAt(i);
            if (item.startsWith(supplierCode)) {
                suppCombo.setSelectedIndex(i);
                break;
            }
        }
        
        // Set product combo
        for (int i = 0; i < prodCombo.getItemCount(); i++) {
            String item = prodCombo.getItemAt(i);
            if (item.startsWith(productCode + " - ")) {
                prodCombo.setSelectedIndex(i);
                break;
            }
        }
        
        // Set product name and get brand from product
        nameText.setText(productName);
        try {
            ResultSet rs = new ProductDAO().getProdFromCode(productCode);
            if (rs.next()) {
                brandText.setText(rs.getString("brand"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        quantityText.setText(data[6].toString());
        // Remove dots from cost when populating form field
        costText.setText(data[7].toString().replace(".", ""));
        
        quantity = Integer.parseInt(data[6].toString());
        prodCode = data[2].toString();
    }//GEN-LAST:event_purchaseTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (purchaseTable.getSelectedRow()<0)
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một giao dịch từ bảng.");
        else {
            int opt = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn xóa giao dịch mua hàng này?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
            if(opt==JOptionPane.YES_OPTION) {
                int purchaseId = Integer.parseInt(purchaseTable.getValueAt(purchaseTable.getSelectedRow(),0).toString());
                new ProductDAO().deletePurchaseDAO(purchaseId);
                loadDataSet();
                clearFields();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        productDTO = new Product();
        if (prodCombo.getSelectedIndex() == 0 || jDateChooser1.getDate()==null
            || quantityText.getText().equals(""))
        JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin bắt buộc.");
        else {
            productDTO.setSuppCode(new ProductDAO().getSuppCode(suppCombo.getSelectedItem().toString()));
            String selectedProduct = prodCombo.getSelectedItem().toString();
            String prodCode = selectedProduct.split(" - ")[0];
            productDTO.setProdCode(prodCode);
            try {
                ResultSet resultSet = new ProductDAO().getProdName(prodCode);
                if (resultSet.next()) {
                    // Format date for database (TIMESTAMP format)
                    productDTO.setDate(DateTimeUtil.datePickerToDatabase(jDateChooser1.getDate()));
                    productDTO.setQuantity(Integer.parseInt(quantityText.getText()));
                    Double costPrice = Double.parseDouble(costText.getText());
                    Double totalCost = costPrice * Integer.parseInt(quantityText.getText());
                    productDTO.setTotalCost(totalCost);
                    productDTO.setCostPrice(costPrice);

                    new ProductDAO().addPurchaseDAO(productDTO);
                    loadDataSet();
                    clearFields();
                } else
                JOptionPane.showMessageDialog(null, "Sản phẩm này chưa được thêm vào hệ thống.\nVui lòng thêm sản phẩm trong mục \"Sản phẩm\" trước.");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void prodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodComboActionPerformed
        if (prodCombo.getSelectedIndex() > 0) {
            try {
                String selectedProduct = prodCombo.getSelectedItem().toString();
                String prodCode = selectedProduct.split(" - ")[0];
                ResultSet resultSet = new ProductDAO().getProdFromCode(prodCode);
                if (resultSet.next()) {
                    nameText.setText(resultSet.getString("product_name"));
                    brandText.setText(resultSet.getString("brand"));

                    // Get cost price from latest purchase
                    Double costPrice = new ProductDAO().getProdCost(prodCode);
                    if (costPrice != null) {
                        costText.setText(String.valueOf((long)costPrice.doubleValue()));
                    } else {
                        costText.setText("");
                    }
                } else {
                    nameText.setText("");
                    costText.setText("");
                    brandText.setText("");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_prodComboActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    // Method to load and update combo box containing supplier names
    public void loadComboBox() {
        try {
            SupplierDAO supplierDAO = new SupplierDAO();
            suppCombo.setModel(supplierDAO.setComboItems(supplierDAO.getQueryResult()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    // Method to load product combo box
    public void loadProductComboBox() {
        try {
            ProductDAO productDAO = new ProductDAO();
            prodCombo.setModel(productDAO.setComboItems(productDAO.getQueryResult()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Helper method to format date string
    private String formatDate(String dateStr) {
        if (dateStr == null || dateStr.isEmpty()) {
            return dateStr;
        }
        
        // If already in dd/MM/yyyy format, return as is
        if (dateStr.matches("\\d{2}/\\d{2}/\\d{4}.*")) {
            return dateStr;
        }
        
        // Try to parse from various formats
        try {
            // Try TIMESTAMP format from database first (yyyy-MM-dd HH:mm:ss)
            java.util.Date date = DateTimeUtil.parseDatabaseFormat(dateStr);
            if (date != null) {
                return DateTimeUtil.formatForDisplay(date);
            }
            
            // Try old format for backward compatibility
            String dateWithoutTZ = dateStr.replaceAll(" [A-Z]{2,4} (\\d{4})", " $1");
            SimpleDateFormat oldFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss yyyy", java.util.Locale.ENGLISH);
            date = oldFormat.parse(dateWithoutTZ);
            return DateTimeUtil.formatForDisplay(date);
        } catch (Exception e) {
            // If parsing fails, return original string
            e.printStackTrace();
            return dateStr;
        }
    }
    
    // Method to load data into table
    public void loadDataSet() {
        try {
            ProductDAO productDAO = new ProductDAO();
            ResultSet rs = productDAO.getPurchaseInfo();
            tblModel.setRowCount(0);
            while (rs.next()) {
                String purchaseId = rs.getString(1);
                String productCode = rs.getString(2);
                String productName = rs.getString(3);
                String date = formatDate(rs.getString(4));
                int quantity = rs.getInt(5);
                double costPrice = rs.getDouble(6);
                double totalCost = rs.getDouble(7);
                String formattedCostPrice = formatter.format(costPrice).replace(",", ".");
                String formattedTotalCost = formatter.format(totalCost).replace(",", ".");
                String supplierCode = rs.getString(8);
                String supplierName = rs.getString(9);
                tblModel.addRow(new Object[]{purchaseId, date, productCode, productName, supplierCode, supplierName, quantity, formattedCostPrice, formattedTotalCost});
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    // Method to display search result in table
    public void loadSearchData(String text) {
        try {
            ProductDAO productDAO = new ProductDAO();
            ResultSet rs = productDAO.getPurchaseSearch(text);
            tblModel.setRowCount(0);
            while (rs.next()) {
                String purchaseId = rs.getString(1);
                String productCode = rs.getString(2);
                String productName = rs.getString(3);
                String date = formatDate(rs.getString(4));
                int quantity = rs.getInt(5);
                double costPrice = rs.getDouble(6);
                double totalCost = rs.getDouble(7);
                String formattedCostPrice = formatter.format(costPrice).replace(",", ".");
                String formattedTotalCost = formatter.format(totalCost).replace(",", ".");
                String supplierCode = rs.getString(8);
                String supplierName = rs.getString(9);
                tblModel.addRow(new Object[]{purchaseId, date, productCode, productName, supplierCode, supplierName, quantity, formattedCostPrice, formattedTotalCost});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandText;
    private javax.swing.JTextField costText;
    private javax.swing.JButton deleteButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameText;
    private javax.swing.JComboBox<String> prodCombo;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JTable purchaseTable;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JComboBox<String> suppCombo;
    // End of variables declaration//GEN-END:variables
}
