package UI;

import DAO.CustomerDAO;
import DAO.ProductDAO;
import Model.Product;
import Util.DateTimeUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

public class SalesPage extends javax.swing.JPanel {

    String username;
    Dashboard dashboard;
    int quantity;
    String prodCode;
    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form SalesPage
     */
    
    public SalesPage(String username, Dashboard dashboard) {
        initComponents();
        this.username = username;
        this.dashboard = dashboard;
        salesTable.setDefaultEditor(Object.class, null);
        salesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        initTable();
        custNameLabel.setVisible(false);
        prodNameLabel.setVisible(false);
        loadCustomerComboBox();
        loadProductComboBox();
        loadDataSet();
    }
    
    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã bán", "Ngày", "Mã SP", "Tên SP", "Mã KH", "Tên KH", "Số lượng", "Doanh thu", "Người bán"};
        tblModel.setColumnIdentifiers(headerTbl);
        salesTable.setModel(tblModel);
        salesTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        salesTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        salesTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        salesTable.getColumnModel().getColumn(3).setPreferredWidth(200);
        salesTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        salesTable.getColumnModel().getColumn(5).setPreferredWidth(200);
        salesTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        salesTable.getColumnModel().getColumn(7).setPreferredWidth(150);
        salesTable.getColumnModel().getColumn(8).setPreferredWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sellPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        custCombo = new javax.swing.JComboBox<>();
        prodCombo = new javax.swing.JComboBox<>();
        priceText = new javax.swing.JTextField();
        quantityText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        sellButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addCustButton = new javax.swing.JButton();
        custNameLabel = new javax.swing.JLabel();
        prodNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel1.setText("BÁN HÀNG");

        sellPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bán hàng"));

        jLabel2.setText("Mã KH");

        jLabel3.setText("Mã Sản phẩm");

        jLabel4.setText("Ngày:");

        jLabel5.setText("Giá bán:");

        jLabel6.setText("Số lượng");

        custCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn khách hàng" }));
        custCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custComboActionPerformed(evt);
            }
        });

        prodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn sản phẩm" }));
        prodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodComboActionPerformed(evt);
            }
        });

        sellButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sellButton.setText("BÁN");
        sellButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xóa");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addCustButton.setText("Thêm Khách hàng mới");
        addCustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustButtonActionPerformed(evt);
            }
        });

        custNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custNameLabel.setLabelFor(custCombo);

        prodNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodNameLabel.setLabelFor(prodCombo);

        javax.swing.GroupLayout sellPanelLayout = new javax.swing.GroupLayout(sellPanel);
        sellPanel.setLayout(sellPanelLayout);
        sellPanelLayout.setHorizontalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCustButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addComponent(sellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityText))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceText))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sellPanelLayout.setVerticalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(addCustButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTable);

        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });

        jLabel7.setText("Tìm kiếm");

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("LÀM MỚI");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sellPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (salesTable.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một mục từ bảng để xóa.");
        else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "Bạn có chắc chắn muốn xóa doanh số này khỏi cơ sở dữ liệu?",
                    "Xác nhận",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                new ProductDAO().deleteSaleDAO(Integer.parseInt(
                        salesTable.getValueAt(salesTable.getSelectedRow(),0).toString()));
                loadDataSet();
                clearFields();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearFields() {
        custCombo.setSelectedIndex(0);
        custNameLabel.setText("");
        custNameLabel.setVisible(false);
        prodCombo.setSelectedIndex(0);
        prodNameLabel.setText("");
        prodNameLabel.setVisible(false);
        jDateChooser1.setDate(null);
        priceText.setText("");
        quantityText.setText("");
    }

    private void addCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustButtonActionPerformed
        dashboard.addCustPage();
    }//GEN-LAST:event_addCustButtonActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        if (custCombo.getSelectedIndex() == 0 || prodCombo.getSelectedIndex() == 0
                || jDateChooser1.getDate()==null || quantityText.getText().equals("") || priceText.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ các trường bắt buộc.");
        else {
            try {
                String selectedCustomer = custCombo.getSelectedItem().toString();
                String custCode = selectedCustomer.split(" - ")[0];
                String selectedProduct = prodCombo.getSelectedItem().toString();
                String prodCode = selectedProduct.split(" - ")[0];
                
                Product productDTO = new Product();
                productDTO.setCustCode(custCode);
                // Format date for database (TIMESTAMP format)
                productDTO.setDate(DateTimeUtil.datePickerToDatabase(jDateChooser1.getDate()));
                productDTO.setProdCode(prodCode);
                Double sellPrice = Double.parseDouble(priceText.getText());
                Double totalRevenue = sellPrice * Integer.parseInt(quantityText.getText());
                productDTO.setSellPrice(sellPrice);
                productDTO.setTotalRevenue(totalRevenue);
                productDTO.setQuantity(Integer.parseInt(quantityText.getText()));
                new ProductDAO().sellProductDAO(productDTO, username);
                loadDataSet();
                clearFields();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_sellButtonActionPerformed

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        int row = salesTable.getSelectedRow();
        int col = salesTable.getColumnCount();
        Object[] data = new Object[col];
        for (int i=0; i<col; i++)
            data[i] = salesTable.getValueAt(row, i);
        
        // Get data from table columns
        String customerCode = data[4].toString();
        String productCode = data[2].toString();
        String dateStr = data[1].toString();
        
        // Set customer combo
        for (int i = 0; i < custCombo.getItemCount(); i++) {
            if (custCombo.getItemAt(i).startsWith(customerCode + " - ")) {
                custCombo.setSelectedIndex(i);
                break;
            }
        }
        
        // Set product combo
        for (int i = 0; i < prodCombo.getItemCount(); i++) {
            if (prodCombo.getItemAt(i).startsWith(productCode + " - ")) {
                prodCombo.setSelectedIndex(i);
                break;
            }
        }
        
        // Set date
        try {
            // Parse display format to set date picker
            java.util.Date date = DateTimeUtil.parseDisplayFormat(formatDate(dateStr));
            if (date != null) {
                jDateChooser1.setDate(date);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Get sell price from database
        try {
            ProductDAO productDAO = new ProductDAO();
            ResultSet rs = productDAO.getSalesInfo();
            int currentRow = 0;
            while (rs.next() && currentRow <= row) {
                if (currentRow == row) {
                    double sellPrice = rs.getDouble(10);
                    
                    // Set price without separator
                    priceText.setText(String.valueOf((long)sellPrice));
                    
                    break;
                }
                currentRow++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        quantityText.setText(data[6].toString());
        quantity = Integer.parseInt(data[6].toString());
        prodCode = data[2].toString();
    }//GEN-LAST:event_salesTableMouseClicked
    
    // Helper method to format date string
    private String formatDate(String dateStr) {
        if (dateStr == null || dateStr.isEmpty()) {
            return dateStr;
        }
        
        // If already in dd/MM/yyyy format, return as is
        if (dateStr.matches("\\d{2}/\\d{2}/\\d{4}.*")) {
            return dateStr;
        }
        
        // Try to parse from various formats
        try {
            // Try TIMESTAMP format from database first (yyyy-MM-dd HH:mm:ss)
            java.util.Date date = DateTimeUtil.parseDatabaseFormat(dateStr);
            if (date != null) {
                return DateTimeUtil.formatForDisplay(date);
            }
            
            // Try old format for backward compatibility
            String dateWithoutTZ = dateStr.replaceAll(" [A-Z]{2,4} (\\d{4})", " $1");
            SimpleDateFormat oldFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss yyyy", java.util.Locale.ENGLISH);
            date = oldFormat.parse(dateWithoutTZ);
            return DateTimeUtil.formatForDisplay(date);
        } catch (Exception e) {
            return dateStr;
        }
    }

    private void custComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custComboActionPerformed
        if (custCombo.getSelectedIndex() > 0) {
            try {
                String selectedCustomer = custCombo.getSelectedItem().toString();
                String custCode = selectedCustomer.split(" - ")[0];
                ResultSet resultSet = new CustomerDAO().getCustName(custCode);
                if (resultSet.next()) {
                    String fullName = resultSet.getString("full_name");
                    String location = resultSet.getString("location");
                    custNameLabel.setText("Tên: " + fullName + " | Địa chỉ: " + location);
                } else {
                    custNameLabel.setText("||   Khách hàng không tồn tại trong cơ sở dữ liệu.   ||");
                }
                custNameLabel.setVisible(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            custNameLabel.setText("");
            custNameLabel.setVisible(false);
        }
    }//GEN-LAST:event_custComboActionPerformed

    private void prodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodComboActionPerformed
        if (prodCombo.getSelectedIndex() > 0) {
            try {
                String selectedProduct = prodCombo.getSelectedItem().toString();
                String prodCode = selectedProduct.split(" - ")[0];
                ResultSet resultSet = new CustomerDAO().getProdName(prodCode);
                if (resultSet.next()) {
                    String productName = resultSet.getString("product_name");
                    int availableQty = resultSet.getInt("quantity");
                    prodNameLabel.setText("Tên: " + productName + " | Số lượng có sẵn: " + availableQty);
                    Double sellPrice = new ProductDAO().getProdSell(prodCode);
                    if (sellPrice != null) {
                        priceText.setText(String.valueOf((long)sellPrice.doubleValue()));
                    } else {
                        // If no previous sell price, use cost price as reference
                        double costPrice = resultSet.getDouble("cost_price");
                        if (costPrice > 0) {
                            priceText.setText(String.valueOf((long)costPrice));
                        } else {
                            priceText.setText(""); // Leave empty for user to enter
                        }
                    }
                } else {
                    prodNameLabel.setText("||   Sản phẩm không tồn tại trong kho.  ||");
                }
                prodNameLabel.setVisible(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            prodNameLabel.setText("");
            prodNameLabel.setVisible(false);
            priceText.setText("");
        }
    }//GEN-LAST:event_prodComboActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadDataSet();
        clearFields();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        loadSearchData(searchText.getText());
    }//GEN-LAST:event_searchTextKeyReleased

    // Method to load customer combo box
    public void loadCustomerComboBox() {
        try {
            CustomerDAO customerDAO = new CustomerDAO();
            custCombo.setModel(customerDAO.setComboItems(customerDAO.getQueryResult()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    // Method to load product combo box
    public void loadProductComboBox() {
        try {
            ProductDAO productDAO = new ProductDAO();
            prodCombo.setModel(productDAO.setComboItems(productDAO.getQueryResult()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Method to load data into table
    public void loadDataSet() {
        try {
            ProductDAO productDAO = new ProductDAO();
            ResultSet rs = productDAO.getSalesInfo();
            tblModel.setRowCount(0);
            while (rs.next()) {
                String salesCode = rs.getString(1);
                String productCode = rs.getString(2);
                String productName = rs.getString(3);
                String customerCode = rs.getString(4);
                String customerName = rs.getString(5);
                int quantity = rs.getInt(6);
                double revenue = rs.getDouble(7);
                String formattedRevenue = formatter.format(revenue).replace(",", ".");
                String soldBy = rs.getString(8);
                String date = formatDate(rs.getString(9));
                tblModel.addRow(new Object[]{salesCode, date, productCode, productName, customerCode, customerName, quantity, formattedRevenue, soldBy});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Method to display search result in table
    public void loadSearchData(String text) {
        try {
            ProductDAO productDAO = new ProductDAO();
            ResultSet rs = productDAO.getSalesSearch(text);
            tblModel.setRowCount(0);
            while (rs.next()) {
                String salesCode = rs.getString(1);
                String productCode = rs.getString(2);
                String productName = rs.getString(3);
                String customerCode = rs.getString(4);
                String customerName = rs.getString(5);
                int quantity = rs.getInt(6);
                double revenue = rs.getDouble(7);
                String formattedRevenue = formatter.format(revenue).replace(",", ".");
                String soldBy = rs.getString(8);
                String date = formatDate(rs.getString(9));
                tblModel.addRow(new Object[]{salesCode, date, productCode, productName, customerCode, customerName, quantity, formattedRevenue, soldBy});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustButton;
    private javax.swing.JComboBox<String> custCombo;
    private javax.swing.JLabel custNameLabel;
    private javax.swing.JButton deleteButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField priceText;
    private javax.swing.JComboBox<String> prodCombo;
    private javax.swing.JLabel prodNameLabel;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable salesTable;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton sellButton;
    private javax.swing.JPanel sellPanel;
    // End of variables declaration//GEN-END:variables
}
