package View;

import DAO.StatisticsDAO;
import Util.IconScaler;
import Util.ThemeUtil;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;

public class HomePage extends javax.swing.JPanel {

    String username;
    private StatisticsDAO statisticsDAO;
    private DecimalFormat formatter = new DecimalFormat("###,###,###");

    // Statistics value labels
    private JLabel revenueValue, costValue, profitValue;
    private JLabel productsValue, stockValue, inventoryValue;
    private JLabel customersValue, suppliersValue, salesValue;
    private JLabel purchasesValue, lowStockValue;

    // Chart panels
    private ChartPanel revenueChartPanel;
    private ChartPanel topProductsChartPanel;
    
    // Content panel
    private JPanel contentPanel;

    /**
     * Creates new form StatsPage
     */

    public HomePage(String username) {
        initComponents();
        this.username = username;
        statisticsDAO = new StatisticsDAO();
        refreshButton.setIcon(IconScaler.scaleIcon16("/View/Icons/refresh.png"));
        setupStatistics();
        applyTheme();
        loadStatistics();
        updateCharts();
    }

    // Apply theme to all components
    private void applyTheme() {
        // Apply white background to panels
        ThemeUtil.applyWhiteBackground(this);
        if (contentPanel != null) {
            ThemeUtil.applyWhiteBackground(contentPanel);
        }
        
        // Apply refresh button style
        ThemeUtil.applyRefreshButtonStyle(refreshButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        refreshButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel1.setText("THỐNG KÊ");
        jLabel1.setToolTipText("");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/refresh.png"))); // NOI18N
        refreshButton.setText("LÀM MỚI");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        408, Short.MAX_VALUE)
                                                .addComponent(refreshButton)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshButtonActionPerformed
        loadStatistics();
        updateCharts();
    }// GEN-LAST:event_refreshButtonActionPerformed

    private void setupStatistics() {
        // Create main content panel with explicit preferred height
        contentPanel = new JPanel();
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Financial Section
        contentPanel.add(createSectionLabel("TỔNG QUAN TÀI CHÍNH"));
        contentPanel.add(Box.createRigidArea(new Dimension(0, 5)));

        JPanel financialPanel = new JPanel(new GridLayout(1, 3, 8, 0));
        financialPanel.setOpaque(false);
        financialPanel.setMaximumSize(new Dimension(650, 80));

        JPanel revenueCard = createStatCard("Tổng Doanh Thu", new Color(46, 204, 113));
        revenueValue = (JLabel) revenueCard.getComponent(0);

        JPanel costCard = createStatCard("Tổng Chi Phí", new Color(231, 76, 60));
        costValue = (JLabel) costCard.getComponent(0);

        JPanel profitCard = createStatCard("Lợi Nhuận", new Color(52, 152, 219));
        profitValue = (JLabel) profitCard.getComponent(0);

        financialPanel.add(revenueCard);
        financialPanel.add(costCard);
        financialPanel.add(profitCard);
        contentPanel.add(financialPanel);
        contentPanel.add(Box.createRigidArea(new Dimension(0, 8)));

        // Inventory Section
        contentPanel.add(createSectionLabel("KHO HÀNG"));
        contentPanel.add(Box.createRigidArea(new Dimension(0, 5)));

        JPanel inventoryPanel = new JPanel(new GridLayout(1, 3, 8, 0));
        inventoryPanel.setOpaque(false);
        inventoryPanel.setMaximumSize(new Dimension(650, 80));

        JPanel productsCard = createStatCard("Tổng Sản Phẩm", new Color(155, 89, 182));
        productsValue = (JLabel) productsCard.getComponent(0);

        JPanel stockCard = createStatCard("Tổng Số Lượng", new Color(52, 73, 94));
        stockValue = (JLabel) stockCard.getComponent(0);

        JPanel inventoryValueCard = createStatCard("Giá Trị Kho", new Color(22, 160, 133));
        inventoryValue = (JLabel) inventoryValueCard.getComponent(0);

        inventoryPanel.add(productsCard);
        inventoryPanel.add(stockCard);
        inventoryPanel.add(inventoryValueCard);
        contentPanel.add(inventoryPanel);
        contentPanel.add(Box.createRigidArea(new Dimension(0, 8)));

        // Partners Section
        contentPanel.add(createSectionLabel("ĐỐI TÁC KINH DOANH"));
        contentPanel.add(Box.createRigidArea(new Dimension(0, 5)));

        JPanel partnersPanel = new JPanel(new GridLayout(1, 2, 8, 0));
        partnersPanel.setOpaque(false);
        partnersPanel.setMaximumSize(new Dimension(425, 80));

        JPanel customersCard = createStatCard("Khách Hàng", new Color(241, 196, 15));
        customersValue = (JLabel) customersCard.getComponent(0);

        JPanel suppliersCard = createStatCard("Nhà Cung Cấp", new Color(230, 126, 34));
        suppliersValue = (JLabel) suppliersCard.getComponent(0);

        partnersPanel.add(customersCard);
        partnersPanel.add(suppliersCard);
        contentPanel.add(partnersPanel);
        contentPanel.add(Box.createRigidArea(new Dimension(0, 8)));

        // Transactions Section
        contentPanel.add(createSectionLabel("GIAO DỊCH"));
        contentPanel.add(Box.createRigidArea(new Dimension(0, 5)));

        JPanel transactionsPanel = new JPanel(new GridLayout(1, 3, 8, 0));
        transactionsPanel.setOpaque(false);
        transactionsPanel.setMaximumSize(new Dimension(650, 80));

        JPanel salesCard = createStatCard("Đơn Bán Hàng", new Color(26, 188, 156));
        salesValue = (JLabel) salesCard.getComponent(0);

        JPanel purchasesCard = createStatCard("Đơn Nhập Hàng", new Color(52, 152, 219));
        purchasesValue = (JLabel) purchasesCard.getComponent(0);

        JPanel lowStockCard = createStatCard("Sắp Hết Hàng", new Color(192, 57, 43));
        lowStockValue = (JLabel) lowStockCard.getComponent(0);

        transactionsPanel.add(salesCard);
        transactionsPanel.add(purchasesCard);
        transactionsPanel.add(lowStockCard);
        contentPanel.add(transactionsPanel);
        contentPanel.add(Box.createRigidArea(new Dimension(0, 20)));

        // Charts Section
        contentPanel.add(createSectionLabel("BIỂU ĐỒ PHÂN TÍCH"));
        contentPanel.add(Box.createRigidArea(new Dimension(0, 10)));

        // Chart panels container - 2 rows, 1 column for full width
        JPanel chartsPanel = new JPanel(new GridLayout(2, 1, 0, 15));
        chartsPanel.setOpaque(false);
        chartsPanel.setMaximumSize(new Dimension(680, 650));

        // Initialize chart panels
        revenueChartPanel = createRevenueChart();
        topProductsChartPanel = createTopProductsChart();

        chartsPanel.add(revenueChartPanel);
        chartsPanel.add(topProductsChartPanel);
        contentPanel.add(chartsPanel);

        // Add small space at bottom
        contentPanel.add(Box.createRigidArea(new Dimension(0, 20)));

        // Add content panel to the existing scroll pane
        jScrollPane1.setViewportView(contentPanel);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        // Force layout update
        revalidate();
        repaint();
    }

    private JLabel createSectionLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(new Font("Helvetica Neue", Font.BOLD, 15));
        label.setForeground(new Color(44, 62, 80));
        label.setAlignmentX(Component.CENTER_ALIGNMENT);
        return label;
    }

    private JPanel createStatCard(String title, Color valueColor) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(204, 204, 204), 1),
                BorderFactory.createEmptyBorder(6, 6, 6, 6)));

        // Value (will be updated later)
        JLabel valueLabel = new JLabel("0");
        valueLabel.setFont(new Font("Helvetica Neue", Font.BOLD, 18));
        valueLabel.setForeground(valueColor);
        valueLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        card.add(valueLabel);

        card.add(Box.createRigidArea(new Dimension(0, 3)));

        // Title
        JLabel titleLabel = new JLabel(title);
        titleLabel.setFont(new Font("Helvetica Neue", Font.PLAIN, 10));
        titleLabel.setForeground(new Color(0, 0, 0));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        card.add(titleLabel);

        return card;
    }

    private void loadStatistics() {
        // Load in background thread
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            private double revenue, cost, profit, invValue;
            private int products, stock, customers, suppliers, sales, purchases, lowStock;

            @Override
            protected Void doInBackground() {
                revenue = statisticsDAO.getTotalRevenue();
                cost = statisticsDAO.getTotalPurchaseCost();
                profit = statisticsDAO.getTotalProfit();
                products = statisticsDAO.getTotalProducts();
                stock = statisticsDAO.getTotalStock();
                invValue = statisticsDAO.getTotalInventoryValue();
                customers = statisticsDAO.getTotalCustomers();
                suppliers = statisticsDAO.getTotalSuppliers();
                sales = statisticsDAO.getTotalSales();
                purchases = statisticsDAO.getTotalPurchases();
                lowStock = statisticsDAO.getLowStockCount();
                return null;
            }

            @Override
            protected void done() {
                revenueValue.setText(formatMoney(revenue));
                costValue.setText(formatMoney(cost));
                profitValue.setText(formatMoney(profit));
                productsValue.setText(String.valueOf(products));
                stockValue.setText(String.valueOf(stock));
                inventoryValue.setText(formatMoney(invValue));
                customersValue.setText(String.valueOf(customers));
                suppliersValue.setText(String.valueOf(suppliers));
                salesValue.setText(String.valueOf(sales));
                purchasesValue.setText(String.valueOf(purchases));
                lowStockValue.setText(String.valueOf(lowStock));
            }
        };
        worker.execute();
    }

    private String formatMoney(double amount) {
        return formatter.format(amount).replace(",", ".") + " đ";
    }

    /**
     * Create revenue trend chart (Line chart)
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    private ChartPanel createRevenueChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Add sample data - will be updated when loadStatistics is called
        dataset.addValue(0, "Doanh thu", "Tháng 1");
        dataset.addValue(0, "Doanh thu", "Tháng 2");
        dataset.addValue(0, "Doanh thu", "Tháng 3");
        dataset.addValue(0, "Doanh thu", "Tháng 4");
        dataset.addValue(0, "Doanh thu", "Tháng 5");
        dataset.addValue(0, "Doanh thu", "Tháng 6");

        JFreeChart lineChart = ChartFactory.createLineChart(
                "Xu hướng Doanh Thu 6 Tháng",
                "Tháng",
                "Doanh thu (VNĐ)",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false);

        // Customize chart
        lineChart.setBackgroundPaint(Color.WHITE);
        CategoryPlot plot = lineChart.getCategoryPlot();
        plot.setBackgroundPaint(new Color(245, 245, 245));
        plot.setRangeGridlinePaint(Color.LIGHT_GRAY);

        // Custom Y-axis formatter (K for thousands, M for millions)
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setNumberFormatOverride(new NumberFormat() {
            @Override
            public StringBuffer format(double number, StringBuffer toAppendTo, java.text.FieldPosition pos) {
                if (number >= 1_000_000_000) {
                    return toAppendTo.append(String.format("%.1fB", number / 1_000_000_000));
                } else if (number >= 1_000_000) {
                    return toAppendTo.append(String.format("%.0fM", number / 1_000_000));
                } else if (number >= 1_000) {
                    return toAppendTo.append(String.format("%.0fK", number / 1_000));
                } else {
                    return toAppendTo.append(String.format("%.0f", number));
                }
            }

            @Override
            public StringBuffer format(long number, StringBuffer toAppendTo, java.text.FieldPosition pos) {
                return format((double) number, toAppendTo, pos);
            }

            @Override
            public Number parse(String source, java.text.ParsePosition parsePosition) {
                return null;
            }
        });

        LineAndShapeRenderer renderer = new LineAndShapeRenderer();
        renderer.setSeriesPaint(0, new Color(52, 152, 219));
        renderer.setSeriesStroke(0, new BasicStroke(2.0f));
        plot.setRenderer(renderer);

        ChartPanel chartPanel = new ChartPanel(lineChart);
        chartPanel.setPreferredSize(new Dimension(650, 300));
        return chartPanel;
    }

    /**
     * Create top products pie chart
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    private ChartPanel createTopProductsChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        // Add sample data - will be updated when loadStatistics is called
        dataset.setValue("Sản phẩm 1", 0);
        dataset.setValue("Sản phẩm 2", 0);
        dataset.setValue("Sản phẩm 3", 0);
        dataset.setValue("Sản phẩm 4", 0);
        dataset.setValue("Khác", 0);

        JFreeChart pieChart = ChartFactory.createPieChart(
                "Top 5 Sản Phẩm Bán Chạy",
                dataset,
                true, true, false);

        pieChart.setBackgroundPaint(Color.WHITE);
        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setBackgroundPaint(new Color(245, 245, 245));
        plot.setOutlinePaint(Color.WHITE);

        // Format labels to show percentage
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0}: {2}"));

        plot.setSectionPaint("Sản phẩm 1", new Color(52, 152, 219));
        plot.setSectionPaint("Sản phẩm 2", new Color(46, 204, 113));
        plot.setSectionPaint("Sản phẩm 3", new Color(155, 89, 182));
        plot.setSectionPaint("Sản phẩm 4", new Color(241, 196, 15));
        plot.setSectionPaint("Khác", new Color(149, 165, 166));

        ChartPanel chartPanel = new ChartPanel(pieChart);
        chartPanel.setPreferredSize(new Dimension(650, 300));
        return chartPanel;
    }

    /**
     * Update charts with real data
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    private void updateCharts() {
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            private DefaultCategoryDataset revenueDataset;
            private DefaultPieDataset topProductsDataset;

            @Override
            protected Void doInBackground() {
                // Update revenue chart data (ordered from oldest to newest, left to right)
                revenueDataset = new DefaultCategoryDataset();
                try {
                    ResultSet rs = statisticsDAO.getRevenueVsCost(6);
                    while (rs != null && rs.next()) {
                        String month = rs.getString("month");
                        double revenue = rs.getDouble("revenue");
                        // Format month from "yyyy-MM" to "MM/yyyy"
                        String formattedMonth = formatMonthLabel(month);
                        revenueDataset.addValue(revenue, "Doanh thu", formattedMonth);
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }

                // Update top products chart data
                topProductsDataset = new DefaultPieDataset();
                try {
                    ResultSet rs = statisticsDAO.getTopSellingProducts(5);
                    int count = 0;
                    while (rs != null && rs.next() && count < 5) {
                        String productName = rs.getString("product_name");
                        int quantity = rs.getInt("total_quantity");
                        if (quantity > 0) {
                            topProductsDataset.setValue(productName, quantity);
                            count++;
                        }
                    }
                    // Add "Khác" category if less than 5 products
                    if (count < 5) {
                        topProductsDataset.setValue("Khác", 0);
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void done() {
                // Update revenue chart
                JFreeChart revenueChart = revenueChartPanel.getChart();
                CategoryPlot revenuePlot = revenueChart.getCategoryPlot();
                revenuePlot.setDataset(revenueDataset);

                // Update top products chart
                JFreeChart topProductsChart = topProductsChartPanel.getChart();
                PiePlot piePlot = (PiePlot) topProductsChart.getPlot();
                piePlot.setDataset(topProductsDataset);

                // Update colors for pie sections
                int sectionIndex = 0;
                Color[] colors = {
                        new Color(52, 152, 219),
                        new Color(46, 204, 113),
                        new Color(155, 89, 182),
                        new Color(241, 196, 15),
                        new Color(149, 165, 166)
                };
                @SuppressWarnings("unchecked")
                java.util.List<Comparable<?>> keys = topProductsDataset.getKeys();
                for (Comparable<?> key : keys) {
                    piePlot.setSectionPaint(key, colors[sectionIndex % colors.length]);
                    sectionIndex++;
                }
            }
        };
        worker.execute();
    }

    /**
     * Format month label from "yyyy-MM" to "MM/yyyy"
     * Example: "2026-01" -> "01/2026"
     */
    private String formatMonthLabel(String month) {
        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM");
            SimpleDateFormat outputFormat = new SimpleDateFormat("MM/yyyy");
            return outputFormat.format(inputFormat.parse(month));
        } catch (ParseException e) {
            // If parsing fails, return original string
            return month;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
